[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  YARN_VERSION = "1.22.22"
  YARN_FLAGS = "--network-timeout 600000 --registry https://registry.npmjs.org"