[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  YARN_VERSION = "1.22.22"
  YARN_FLAGS = "--network-timeout 600000 --registry https://registry.npmjs.org"
  VITE_API_URL = "https://onlyflansbackend.onrender.com/api"
  VITE_CLOUDINARY_CLOUD_NAME = "df0iakdao"
  VITE_CLOUDINARY_UPLOAD_PRESET = "onlyflans_unsigned"
  VITE_CLOUDINARY_FOLDER = "onlyflans"
